server:
  port: 8082
  servlet:
    context-path: /manage
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/boat?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
#    url: jdbc:p6spy:mysql://localhost:3306/boat?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启目录
      additional-paths: src/main/java